title:              "BVN Styleguide"
email:              "someone@bvn.com.au"
description:        "BVN's graphical guidelines."
description_body:   "We've open sourced our style guide as a step towards making the industry less opaque. Please fork the repository and make your own version, or even better, contribute back to this one!"
image:              "http://bvn-architecture.github.io/styleguide/assets/bvn-logo-meta.jpeg"
date:               2015-11-30T17:52:48+11:00

baseurl:            ""
url:                "http://manuals.bvn.com.au" # the base hostname & protocol for your site
#host:                localhost
#source:  src
#exclude: ['src/bower_components']title:              "BVN Styleguide"


twitter_username:   "architecturebvn"
github_username:    "bvn-architecture"
facebook_username:  "BVN-Architecture"
facebook_publisher: "https://www.facebook.com/pages/BVN-Architecture/131354776914013?fref=ts"
insta_username:     "architecturebvn"
linkedin_username:  "bvn-architecture"
publisher:          "BVN"
publisher_website:  "http://bvn.com.au/"

edit_symbol: ∞×

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ["tables"]

encoding:     "utf-8"
permalink:    :title
highlighter:  "rouge"

sass:
    sass_dir: _sass

gems:
  - jemoji
